name: shoesexe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  carousel_slider: 4.2.1
  cloud_firestore: 4.3.0
  cupertino_icons: ^1.0.2
  dio: 4.0.6
  dropdown_search: 5.0.5
  firebase_auth: 4.2.4
  firebase_core: 2.4.1
  firebase_storage: 11.0.10
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  get: 4.6.5
  get_storage: 2.0.3
  google_fonts: 3.0.1
  google_sign_in: 5.4.3
  http: 0.13.5
  image_picker: 0.8.6+1
  intl: 0.17.0
  introduction_screen: 3.1.1
  lottie: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logo/
    - assets/lotties/
    - assets/images/
    - assets/produk/
  uses-material-design: true
